require('dotenv').config();
const express  = require('express');
const path     = require('path');
const fs       = require('fs');
const { Client, GatewayIntentBits, Partials } = require('discord.js');

const app  = express();
const PORT = process.env.PORT || 3000;

const LICENSES_FILE = path.join(__dirname, 'licenses.json');

// ── License helpers ────────────────────────────────────
function loadLicenses() {
  try {
    if (!fs.existsSync(LICENSES_FILE)) return [];
    return JSON.parse(fs.readFileSync(LICENSES_FILE, 'utf8'));
  } catch { return []; }
}
function saveLicenses(data) {
  fs.writeFileSync(LICENSES_FILE, JSON.stringify(data, null, 2));
}
function genCode() {
  const seg = () => Math.random().toString(36).substring(2, 6).toUpperCase();
  return `SYM_${seg()}_${seg()}_${seg()}`;
}

// ── Express ───────────────────────────────────────────
app.use(express.json());
app.use(express.static(path.join(__dirname, 'public')));

// Verify license (login page uses this)
app.post('/verify-license', (req, res) => {
  const { code } = req.body || {};
  if (!code) return res.status(400).json({ message: 'No code provided.' });

  const licenses = loadLicenses();
  const idx = licenses.findIndex(l => l.code === code.trim().toUpperCase());

  if (idx === -1) return res.status(403).json({ message: 'Invalid license code.' });
  if (licenses[idx].status === 'USED') return res.status(403).json({ message: 'License already used.' });

  licenses[idx].status = 'USED';
  licenses[idx].usedAt = new Date().toISOString();
  licenses[idx].usedBy = 'web-login';
  licenses[idx].logs   = licenses[idx].logs || [];
  licenses[idx].logs.push({ when: new Date().toISOString(), by: 'web-login', action: 'used' });
  saveLicenses(licenses);

  return res.json({ ok: true });
});

// List licenses (admin dashboard)
app.get('/licenses', (req, res) => {
  res.json(loadLicenses());
});

// Create license via HTTP (optional)
app.post('/create-license', (req, res) => {
  const licenses = loadLicenses();
  const code = genCode();
  const entry = {
    code,
    status: 'UNUSED',
    createdAt: new Date().toISOString(),
    usedAt: '',
    usedBy: '',
    note: 'created via web',
    creatorId: '',
    creatorTag: '',
    logs: [{ when: new Date().toISOString(), by: 'web', action: 'generated', details: '' }]
  };
  licenses.unshift(entry);
  saveLicenses(licenses);
  res.json(entry);
});

// UID proxy
app.post('/proxy/add_uid', async (req, res) => {
  const TARGET = 'http://cloud.obsidianhosting.xyz:2091/api/free/add_uid';
  try {
    const response = await fetch(TARGET, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(req.body)
    });
    const text = await response.text();
    res.status(response.status).send(text);
  } catch (err) {
    res.status(502).send('Proxy error: ' + err.message);
  }
});

// Health check
app.get('/ping', (req, res) => res.send('pong'));

// Self-ping to keep Render awake
const RENDER_URL = process.env.RENDER_EXTERNAL_URL || null;
setTimeout(() => {
  if (!RENDER_URL) return;
  const ping = () => fetch(`${RENDER_URL}/ping`).catch(() => {});
  ping();
  setInterval(ping, 10 * 60 * 1000);
}, 60 * 1000);

// Catch-all → index.html
app.get('*', (req, res) => {
  res.sendFile(path.join(__dirname, 'public', 'index.html'));
});

app.listen(PORT, () => {
  console.log(`[server] Running on port ${PORT}`);
});

// ── Discord Bot ───────────────────────────────────────
const TOKEN      = process.env.DISCORD_TOKEN;
const CHANNEL_ID = process.env.DISCORD_CHANNEL_ID;

if (!TOKEN) {
  console.warn('[bot] DISCORD_TOKEN not set — bot will not start.');
} else {
  const client = new Client({
    intents: [
      GatewayIntentBits.Guilds,
      GatewayIntentBits.GuildMessages,
      GatewayIntentBits.MessageContent,
      GatewayIntentBits.DirectMessages,
    ],
    partials: [Partials.Channel]
  });

  client.once('ready', () => {
    console.log(`[bot] Logged in as ${client.user.tag}`);
  });

  client.on('messageCreate', async (message) => {
    if (message.author.bot) return;

    const content = message.content.trim().toLowerCase();
    if (content !== '!genlicense' && content !== '/genlicense') return;

    const licenses = loadLicenses();
    const code = genCode();
    const entry = {
      code,
      status: 'UNUSED',
      createdAt: new Date().toISOString(),
      usedAt: '',
      usedBy: '',
      note: `generated by ${message.author.username}`,
      creatorId: message.author.id,
      creatorTag: message.author.username,
      logs: [{
        when: new Date().toISOString(),
        by: message.author.username,
        action: 'generated',
        details: `ID: ${message.author.id}`
      }]
    };
    licenses.unshift(entry);
    saveLicenses(licenses);

    try {
      // Reply in the same channel
      await message.reply(`✅ **New License Generated**\n\`\`\`\n${code}\n\`\`\`\nThis is a one-time code. Use it on the login page.`);

      // Also send to the configured log channel if different
      if (CHANNEL_ID && message.channel.id !== CHANNEL_ID) {
        const logChannel = await client.channels.fetch(CHANNEL_ID).catch(() => null);
        if (logChannel) {
          await logChannel.send(`🔑 License generated by **${message.author.username}**\n\`${code}\``);
        }
      }
    } catch (err) {
      console.error('[bot] Failed to send message:', err.message);
    }
  });

  client.login(TOKEN).catch(err => {
    console.error('[bot] Login failed:', err.message);
  });
}
